version: '3.8'

services:
  chat_redis:
    container_name: chat_redis
    restart: always
    image: redis:6.0-alpine3.16
    volumes:
      - chat_redis_volume:/data

  web_daphne:
    container_name: web_daphne
    build: ./
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - chat_redis
    ports:
      - "8000:8000"
      - "3000:3000"
    command: sh -c "
      python3 manage.py migrate && 
      daphne core.asgi:application --bind 0.0.0.0"
    environment:
      REDIS_HOST: chat_redis
      REDIS_PORT: 6379

volumes:
  chat_redis_volume: