version: '3.8'

services:
  chat_redis:
    container_name: chat_redis
    restart: always
    image: redis:6.0-alpine3.16
    volumes:
      - chat_redis_volume:/data

  web_daphne:
    container_name: web_daphne
    build: ./
    restart: always
    volumes:
      - ./:/chat
    depends_on:
      - chat_redis
    ports:
      - "8000:8000"
      - "3000:3000"
    command: sh -c "
      python3 manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"

volumes:
  chat_redis_volume: